[config]
exclude-merge-commits=true
check-summary-length=false

[matchers]
all="(?:feat|test|fix|refactor)\\(\d*?\\): .*?\n(?:\n?(?:\\* |  ).*?\n)*"

[examples]
a_simple_commit="""
[feat|test|fix|refactor](issue number): A commit message
"""
an_extended_commit="""
[feat|test|fix|refactor](issue number): A commit message

* first line
* second line
* and so on...
"""