version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: gradle :schemas:cleanTest :schemas:test :generator:cleanTest :generator:test
      - store_test_results:
          path: schemas/build/reports/tests/test
      - store_test_results:
          path: generator/build/reports/tests/test
  release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: gradle :schemas:release :generator:release
      - store-artifacts:
          path: schemas/build/libs
      - store-artifacts:
          path: generator/build/libs
workflows:
  version: 2.1
  build_and_test: 
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master
