version: 2 
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: mvn clean test
      - run:
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
      - store_test_results:
          path: ~/cucumber
workflows:
  version: 2
  build_and_test: 
    jobs:
      - build
