version: 2 
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: datahelix-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: datahelix-{{ checksum "pom.xml" }}
      - run: mvn package
workflows:
  version: 2
  build_and_test: 
    jobs:
      - build
