version: 2.1

jobs:
        build:
                docker:
                        - image: circleci/openjdk:8-jdk-browsers
                steps:
                        - run: echo "No-op for gh-pages branch"
