version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle :schemas:test :generator:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - codecov/upload:
          file: schemas/target/jacoco-reports/jacoco.xml
      - codecov/upload:
          file: generator/target/jacoco-reports/jacoco.xml

  verify:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Get gommit binary
          command: |
            mkdir /home/circleci/bin
            wget -O ~/bin/gommit https://github.com/antham/gommit/releases/download/v2.0.0/gommit_linux_386 && chmod 777 ~/bin/gommit
      # Currently non-blocking. Can check CI build to verify success
      - run:
          name: Run gommit
          command: |
            if [[ $CIRCLE_BRANCH != 'master' ]]; \
              then if [[ ~/bin/gommit check range $(git rev-parse origin/master) $CIRCLE_BRANCH != 0 ]]; \
                then echo "valid"; \
                else echo "invalid"; \
              fi; \
            fi; \
            true

  release:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle :schemas:release :generator:release
      - store-artifacts:
          path: schemas/build/libs
      - store-artifacts:
          path: generator/build/libs

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - verify
# TODO: Ensure gradle migration is smooth before introducing release job
#  release:
#    jobs:
#      - release:
#          filters:
#            branches:
#              only: master
