version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: mvn clean test
      - store_test_results:
          path: schemas/target/surefire-reports
      - store_test_results:
          path: generator/target/surefire-reports
      - codecov/upload:
          file: schemas/target/jacoco-reports
      - codecov/upload:
          file: generator/target/jacoco-reports
workflows:
  version: 2.1
  build_and_test: 
    jobs:
      - build
